4 sign up screen
s9uidward/Qelem pull request #22
Opened 2022-05-15 06:30 UTC by Biruk-Tassew

Closes #4

2022-05-15 08:30 UTC, hello-world-was-taken requested changes

2022-05-15 08:30 UTC, hello-world-was-taken commented on qelem/lib/screens/registerUser.dart
> +  // var response = await http.post(Uri.parse(url),
Remove unnecessary comments.

2022-05-15 08:30 UTC, hello-world-was-taken commented on qelem/lib/screens/registerUser.dart
> +  // final path = image.path;
Remove these ones too.

2022-05-15 08:30 UTC, hello-world-was-taken commented on qelem/lib/screens/registerUser.dart
> +              // FloatingActionButton.extended(
These ones too.

2022-05-15 14:01 UTC, nawrazi approved these changes

2022-05-15 17:08 UTC, s9uidward approved these changes

2022-05-16 19:03 UTC, brukted approved these changes

2022-05-16 19:09 UTC, merged